

class RandomGenerator{
	constructor(min, max){
		if(!min && !max) {
			min=1;
			max=10;
		}
		this.min = min;
		this.max = max;
		this.storage = [];
		
		//takes in the minimum and maximum values
		//if they are not defined, it sets the minimum to 1, and the max to 10
		//makes storage for the random number
	}
	generate(){
		var generatedNumber = Math.floor(Math.random()*(this.max-this.min))+this.min;
		console.log(generatedNumber);
		this.storage.push(generatedNumber);
		this.getNum();
		//make a random value between the minimum and maximum values
		//and store the number into the storage from the constructor
	}
	getRange(){
		var min = this.min;
		var max = this.max;
		this.storage.forEach(function(num) {
			if(num < min) {
				min = num;
			} 

			if(num > max) {
				max = num;
			}
		})

		var object = {
			min: min,
			max: max
		}

		return object;
		//return an object with min and max, min being the minimum value for the generator, max being the maximum value
		//returns a basic object literal
	}
	getNum(){
		var num=this.storage[this.storage.length-1];
		return num;
		//return the random number that was generated by generate()
	}
}